import { Tool } from '../swarm/types';
import { exec } from 'child_process';
import { promisify } from 'util';
import fs from 'fs/promises';
import path from 'path';

const execAsync = promisify(exec);

/**
 * Project Scaffolder — generate complete project structures from templates
 */
export const projectScaffolderTool: Tool = {
  type: 'function',
  function: {
    name: 'scaffold_project',
    description: 'Generate complete project structures: Next.js app, Express API, Python Flask, CLI tool, library, or custom. Creates all files, configs, and boilerplate.',
    parameters: {
      type: 'object',
      properties: {
        type: {
          type: 'string',
          enum: ['nextjs', 'express-api', 'fastapi', 'cli', 'library', 'react-vite', 'custom'],
          description: 'Project type to scaffold'
        },
        name: {
          type: 'string',
          description: 'Project name'
        },
        dir: {
          type: 'string',
          description: 'Parent directory for the project (default: sandbox)'
        },
        extras: {
          type: 'string',
          description: 'Extra features to include: "auth,db,tests,docker,ci" (comma-separated)'
        }
      },
      required: ['type', 'name']
    }
  },
  execute: async ({ type, name, dir = '', extras = '' }: {
    type: string; name: string; dir?: string; extras?: string
  }) => {
    try {
      const SAFE_DIR = process.env.SAFE_DIR || path.join(/*turbopackIgnore: true*/ process.cwd(), 'sandbox');
      const baseDir = dir ? path.join(/*turbopackIgnore: true*/ SAFE_DIR, dir) : SAFE_DIR;
      const projectDir = path.join(baseDir, name);
      const features = extras ? extras.split(',').map(f => f.trim()) : [];

      // Generate file tree based on project type
      const fileTree: Record<string, string> = {};

      switch (type) {
        case 'nextjs':
          Object.assign(fileTree, generateNextjsProject(name, features));
          break;
        case 'express-api':
          Object.assign(fileTree, generateExpressProject(name, features));
          break;
        case 'fastapi':
          Object.assign(fileTree, generateFastapiProject(name, features));
          break;
        case 'cli':
          Object.assign(fileTree, generateCliProject(name, features));
          break;
        case 'library':
          Object.assign(fileTree, generateLibraryProject(name, features));
          break;
        case 'react-vite':
          Object.assign(fileTree, generateReactViteProject(name, features));
          break;
        default:
          return `Unknown project type: ${type}. Supported: nextjs, express-api, fastapi, cli, library, react-vite, custom`;
      }

      // Write all files
      const written: string[] = [];
      for (const [relPath, content] of Object.entries(fileTree)) {
        const fullPath = path.join(projectDir, relPath);
        await fs.mkdir(path.dirname(fullPath), { recursive: true });
        await fs.writeFile(fullPath, content, 'utf-8');
        written.push(relPath);
      }

      // Generate output
      let output = `═══ ${type.toUpperCase()} PROJECT: ${name} ═══\n\n`;
      output += `📁 ${name}/\n`;
      output += renderTree(fileTree, '');
      output += `\n✅ ${written.length} files created\n`;
      output += `\nNext steps:\n`;
      output += `  cd ${name}\n`;
      output += getInstallInstructions(type, features);

      return output.trim();
    } catch (err: any) {
      return `Scaffold error: ${err.message}`;
    }
  }
};

function generateNextjsProject(name: string, features: string[]): Record<string, string> {
  const files: Record<string, string> = {
    'package.json': JSON.stringify({
      name,
      version: '0.1.0',
      private: true,
      scripts: { dev: 'next dev', build: 'next build', start: 'next start', lint: 'next lint' },
      dependencies: { next: 'latest', react: '^19', 'react-dom': '^19' },
      devDependencies: { '@types/node': '^20', '@types/react': '^19', '@types/react-dom': '^19', typescript: '^5' }
    }, null, 2),
    'tsconfig.json': JSON.stringify({
      compilerOptions: { target: 'ES2017', lib: ['dom', 'dom.iterable', 'esnext'], allowJs: true, skipLibCheck: true, strict: true, noEmit: true, esModuleInterop: true, module: 'esnext', moduleResolution: 'bundler', resolveJsonModule: true, isolatedModules: true, jsx: 'preserve', incremental: true, plugins: [{ name: 'next' }], paths: { '@/*': ['./src/*'] } },
      include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
      exclude: ['node_modules']
    }, null, 2),
    'next.config.ts': 'import type { NextConfig } from "next";\nconst config: NextConfig = {};\nexport default config;',
    'src/app/layout.tsx': `import type { Metadata } from "next";\nexport const metadata: Metadata = { title: "${name}", description: "Generated by CortisolBoard" };\nexport default function RootLayout({ children }: { children: React.ReactNode }) {\n  return (<html lang="en"><body>{children}</body></html>);\n}`,
    'src/app/page.tsx': `export default function Home() {\n  return (\n    <main style={{ padding: '2rem', maxWidth: '800px', margin: '0 auto' }}>\n      <h1>Welcome to ${name}</h1>\n      <p>Get started by editing src/app/page.tsx</p>\n    </main>\n  );\n}`,
    'src/app/globals.css': 'body { font-family: system-ui, sans-serif; margin: 0; padding: 0; }',
    '.gitignore': 'node_modules\n.next\n.env\n.env.local\ndist\nbuild\n*.local',
    'README.md': `# ${name}\n\nGenerated by CortisolBoard\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n\nOpen [http://localhost:3000](http://localhost:3000)`
  };

  if (features.includes('tests')) {
    files['tests/home.test.tsx'] = `import { describe, it, expect } from 'vitest';\ndescribe('Home Page', () => {\n  it('renders heading', () => {\n    expect(true).toBe(true);\n  });\n});`;
    files['vitest.config.ts'] = `import { defineConfig } from 'vitest/config';\nexport default defineConfig({ test: { environment: 'jsdom', globals: true } });`;
  }

  if (features.includes('docker')) {
    files['Dockerfile'] = `FROM node:20-alpine AS base\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci --only=production\nCOPY . .\nRUN npm run build\nEXPOSE 3000\nCMD ["npm", "start"]`;
    files['.dockerignore'] = 'node_modules\n.next\n.git\ndist';
  }

  if (features.includes('auth')) {
    files['src/lib/auth.ts'] = `import { SignJWT, jwtVerify } from 'jose';\nconst SECRET = new TextEncoder().encode(process.env.SESSION_SECRET || 'dev-secret');\nexport async function createToken(payload: Record<string, any>) {\n  return new SignJWT(payload).setProtectedHeader({ alg: 'HS256' }).setExpirationTime('7d').sign(SECRET);\n}\nexport async function verifyToken(token: string) {\n  return jwtVerify(token, SECRET);\n}`;
  }

  if (features.includes('db')) {
    files['src/lib/db.ts'] = `import { PrismaClient } from '@prisma/client';\nconst globalForPrisma = globalThis as unknown as { prisma: PrismaClient };\nexport const prisma = globalForPrisma.prisma || new PrismaClient();\nif (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = prisma;`;
    files['prisma/schema.prisma'] = `generator client { provider = "prisma-client-js" }\ndatasource db { provider = "sqlite" url = "file:./dev.db" }\n\nmodel User {\n  id        String   @id @default(cuid())\n  email     String   @unique\n  name      String?\n  createdAt DateTime @default(now())\n}`;
  }

  if (features.includes('ci')) {
    files['.github/workflows/ci.yml'] = `name: CI\non: [push, pull_request]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with: { node-version: 20, cache: 'npm' }\n      - run: npm ci\n      - run: npm run build`;
  }

  return files;
}

function generateExpressProject(name: string, features: string[]): Record<string, string> {
  const files: Record<string, string> = {
    'package.json': JSON.stringify({ name, version: '0.1.0', main: 'src/index.ts', scripts: { dev: 'tsx watch src/index.ts', build: 'tsc', start: 'node dist/index.js' }, dependencies: { express: '^4', cors: '^2', 'dotenv': '^16' }, devDependencies: { '@types/express': '^5', '@types/node': '^20', '@types/cors': '^2', tsx: '^4', typescript: '^5' } }, null, 2),
    'tsconfig.json': JSON.stringify({ compilerOptions: { target: 'ES2020', module: 'commonjs', outDir: './dist', rootDir: './src', strict: true, esModuleInterop: true, skipLibCheck: true }, include: ['src/**/*'] }, null, 2),
    'src/index.ts': `import express from 'express';\nimport cors from 'cors';\nimport 'dotenv/config';\n\nconst app = express();\nconst PORT = process.env.PORT || 3000;\n\napp.use(cors());\napp.use(express.json());\n\napp.get('/health', (_req, res) => res.json({ status: 'ok' }));\napp.get('/api', (_req, res) => res.json({ message: '${name} API' }));\n\napp.listen(PORT, () => console.log(\`🚀 Server running on port \${PORT}\`));`,
    '.env': 'PORT=3000\nNODE_ENV=development',
    '.gitignore': 'node_modules\ndist\n.env\n*.log',
    'README.md': `# ${name}\n\nExpress API\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\``
  };

  if (features.includes('tests')) {
    files['tests/api.test.ts'] = `import { describe, it, expect } from 'vitest';\ndescribe('API', () => {\n  it('returns health', () => {\n    expect({ status: 'ok' }).toEqual({ status: 'ok' });\n  });\n});`;
  }

  if (features.includes('auth')) {
    files['src/middleware/auth.ts'] = `import { Request, Response, NextFunction } from 'express';\nexport function authMiddleware(req: Request, res: Response, next: NextFunction) {\n  const token = req.headers.authorization?.split(' ')[1];\n  if (!token) return res.status(401).json({ error: 'Unauthorized' });\n  next();\n}`;
  }

  if (features.includes('docker')) {
    files['Dockerfile'] = `FROM node:20-alpine\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci --only=production\nCOPY . .\nRUN npm run build\nEXPOSE 3000\nCMD ["npm", "start"]`;
  }

  return files;
}

function generateFastapiProject(name: string, features: string[]): Record<string, string> {
  const files: Record<string, string> = {
    'pyproject.toml': `[project]\nname = "${name}"\nversion = "0.1.0"\nrequires-python = ">=3.11"\ndependencies = ["fastapi", "uvicorn[standard]", "pydantic"]`,
    'src/__init__.py': '',
    'src/main.py': `from fastapi import FastAPI\n\napp = FastAPI(title="${name}")\n\n@app.get("/health")\ndef health():\n    return {"status": "ok"}\n\n@app.get("/")\ndef root():\n    return {"message": "${name} API"}`,
    '.env': 'DEBUG=true\nPORT=8000',
    '.gitignore': '__pycache__\n*.pyc\n.env\n.venv\n',
    'README.md': `# ${name}\n\nFastAPI\n\n\`\`\`bash\npip install .\nuvicorn src.main:app --reload\n\`\`\``
  };

  if (features.includes('tests')) {
    files['tests/__init__.py'] = '';
    files['tests/test_main.py'] = `from fastapi.testclient import TestClient\nfrom src.main import app\nclient = TestClient(app)\ndef test_health():\n    r = client.get("/health")\n    assert r.status_code == 200\n    assert r.json() == {"status": "ok"}`;
  }

  if (features.includes('db')) {
    files['src/database.py'] = `from sqlalchemy import create_engine\nfrom sqlalchemy.orm import sessionmaker\n\nDATABASE_URL = "sqlite:///./dev.db"\nengine = create_engine(DATABASE_URL)\nSessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)`;
  }

  if (features.includes('docker')) {
    files['Dockerfile'] = `FROM python:3.12-slim\nWORKDIR /app\nCOPY . .\nRUN pip install .\nEXPOSE 8000\nCMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]`;
  }

  return files;
}

function generateCliProject(name: string, features: string[]): Record<string, string> {
  const files: Record<string, string> = {
    'package.json': JSON.stringify({ name, version: '0.1.0', bin: { [name]: './bin/cli.js' }, dependencies: { commander: '^12', chalk: '^5', ora: '^8' }, devDependencies: { '@types/node': '^20', typescript: '^5', tsx: '^4' } }, null, 2),
    'bin/cli.js': `#!/usr/bin/env node\nconst { program } = require('commander');\n\nprogram\n  .name('${name}')\n  .description('CLI tool generated by CortisolBoard')\n  .version('0.1.0')\n  .command('greet <name>')\n  .description('Greet someone')\n  .action((name) => console.log(\`Hello, \${name}!\`));\n\nprogram.parse();`,
    'README.md': `# ${name}\n\nCLI tool\n\n\`\`\`bash\nnpm install -g .\n${name} greet World\n\`\`\``
  };

  if (features.includes('tests')) {
    files['tests/cli.test.ts'] = `import { describe, it, expect } from 'vitest';\ndescribe('CLI', () => {\n  it('exists', () => { expect(true).toBe(true); });\n});`;
  }

  return files;
}

function generateLibraryProject(name: string, features: string[]): Record<string, string> {
  const files: Record<string, string> = {
    'package.json': JSON.stringify({ name, version: '0.1.0', main: 'dist/index.js', module: 'dist/index.mjs', types: 'dist/index.d.ts', files: ['dist'], scripts: { build: 'tsup src/index.ts --format cjs,esm --dts', dev: 'tsup src/index.ts --watch' }, devDependencies: { typescript: '^5', tsup: '^8' } }, null, 2),
    'tsconfig.json': JSON.stringify({ compilerOptions: { target: 'ES2020', module: 'ESNext', moduleResolution: 'bundler', declaration: true, outDir: 'dist', strict: true }, include: ['src'] }, null, 2),
    'src/index.ts': `export const hello = (name: string): string => \`Hello, \${name}!\`;\n`,
    '.gitignore': 'node_modules\ndist\n*.log',
    'README.md': `# ${name}\n\n\`\`\`bash\nnpm install ${name}\n\`\`\`\n\n\`\`\`typescript\nimport { hello } from '${name}';\nconsole.log(hello('World'));\n\`\`\``
  };

  if (features.includes('tests')) {
    files['tests/index.test.ts'] = `import { describe, it, expect } from 'vitest';\nimport { hello } from '../src';\ndescribe('${name}', () => {\n  it('greets correctly', () => {\n    expect(hello('World')).toBe('Hello, World!');\n  });\n});`;
  }

  if (features.includes('ci')) {
    files['.github/workflows/ci.yml'] = `name: CI\non: [push, pull_request]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with: { node-version: 20, cache: 'npm' }\n      - run: npm ci\n      - run: npm run build`;
  }

  return files;
}

function generateReactViteProject(name: string, features: string[]): Record<string, string> {
  const files: Record<string, string> = {
    'package.json': JSON.stringify({ name, version: '0.1.0', type: 'module', scripts: { dev: 'vite', build: 'tsc -b && vite build', preview: 'vite preview' }, dependencies: { react: '^19', 'react-dom': '^19' }, devDependencies: { '@vitejs/plugin-react': '^4', vite: '^6', typescript: '^5', '@types/react': '^19', '@types/react-dom': '^19' } }, null, 2),
    'vite.config.ts': `import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\nexport default defineConfig({ plugins: [react()] });`,
    'tsconfig.json': JSON.stringify({ compilerOptions: { target: 'ES2020', useDefineForClassFields: true, module: 'ESNext', strict: true, jsx: 'react-jsx' }, include: ['src'] }, null, 2),
    'index.html': `<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8" />\n    <title>${name}</title>\n  </head>\n  <body>\n    <div id="root"></div>\n    <script type="module" src="/src/main.tsx"></script>\n  </body>\n</html>`,
    'src/main.tsx': `import { StrictMode } from 'react';\nimport { createRoot } from 'react-dom/client';\nimport App from './App';\ncreateRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>);`,
    'src/App.tsx': `export default function App() {\n  return (\n    <div style={{ padding: '2rem' }}>\n      <h1>Welcome to ${name}</h1>\n      <p>Start building your React app here.</p>\n    </div>\n  );\n}`,
    '.gitignore': 'node_modules\ndist\n.env\n*.local',
    'README.md': `# ${name}\n\nReact + Vite\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\``
  };

  return files;
}

function renderTree(files: Record<string, string>, prefix: string): string {
  const entries = Object.keys(files).sort();
  let output = '';
  for (let i = 0; i < entries.length; i++) {
    const isLast = i === entries.length - 1;
    const connector = isLast ? '└── ' : '├── ';
    const parts = entries[i].split('/');
    const fileName = parts[parts.length - 1];
    output += `${prefix}${connector}${fileName}\n`;
  }
  return output;
}

function getInstallInstructions(type: string, features: string[]): string {
  const base = `  npm install\n`;
  switch (type) {
    case 'nextjs': return base + `  npm run dev\n\nOpen http://localhost:3000`;
    case 'express-api': return base + `  npm run dev\n\nAPI: http://localhost:3000/api`;
    case 'fastapi': return `  pip install .\n  uvicorn src.main:app --reload\n\nDocs: http://localhost:8000/docs`;
    case 'cli': return base + `  npm link\n  ${'your-cli'} greet World`;
    case 'library': return base + `  npm run build`;
    case 'react-vite': return base + `  npm run dev\n\nOpen http://localhost:5173`;
    default: return base;
  }
}

/**
 * Pipeline Builder — chain commands with conditions, retries, and parallel execution
 */
export const pipelineBuilderTool: Tool = {
  type: 'function',
  function: {
    name: 'run_pipeline',
    description: 'Execute a pipeline of commands with support for sequential/parallel execution, conditions, retries, and output passing between steps.',
    parameters: {
      type: 'object',
      properties: {
        steps: {
          type: 'string',
          description: 'Pipeline steps as JSON array. Each step: {"name": "step1", "cmd": "echo hello", "retry": 2, "condition": "optional shell condition"}'
        },
        mode: {
          type: 'string',
          enum: ['sequential', 'parallel'],
          description: 'Execution mode'
        },
        stopOnError: {
          type: 'boolean',
          description: 'Stop pipeline on first error (default: true)'
        },
        cwd: {
          type: 'string',
          description: 'Working directory for commands (default: sandbox)'
        }
      },
      required: ['steps']
    }
  },
  execute: async ({ steps, mode = 'sequential', stopOnError = true, cwd = '' }: {
    steps: string; mode?: string; stopOnError?: boolean; cwd?: string
  }) => {
    try {
      let parsedSteps: Array<{ name: string; cmd: string; retry?: number; condition?: string }>;
      try {
        parsedSteps = JSON.parse(steps);
      } catch {
        return 'Error: Invalid JSON in steps parameter';
      }

      if (!Array.isArray(parsedSteps) || parsedSteps.length === 0) {
        return 'Error: steps must be a non-empty JSON array';
      }

      const SAFE_DIR = process.env.SAFE_DIR || path.join(process.cwd(), 'sandbox');
      const workDir = cwd || SAFE_DIR;
      await fs.mkdir(workDir, { recursive: true });

      let output = `═══ PIPELINE EXECUTION ═══\n`;
      output += `Mode: ${mode}\n`;
      output += `Steps: ${parsedSteps.length}\n`;
      output += `Working Dir: ${workDir}\n`;
      output += `══════════════════════════\n\n`;

      const results: Array<{ name: string; status: 'SUCCESS' | 'FAILED' | 'SKIPPED'; output?: string; duration?: number }> = [];

      if (mode === 'sequential') {
        for (const step of parsedSteps) {
          // Check condition
          if (step.condition) {
            try {
              await execAsync(step.condition, { cwd: workDir, timeout: 5000 });
            } catch {
              results.push({ name: step.name, status: 'SKIPPED' });
              output += `⏭️  ${step.name}: SKIPPED (condition failed)\n`;
              continue;
            }
          }

          const maxAttempts = (step.retry || 0) + 1;
          let success = false;
          let lastOutput = '';
          let lastDuration = 0;

          for (let attempt = 1; attempt <= maxAttempts; attempt++) {
            const start = Date.now();
            try {
              const { stdout, stderr } = await execAsync(step.cmd, { cwd: workDir, timeout: 30000, maxBuffer: 1024 * 512 });
              lastOutput = (stdout + stderr).trim() || '[no output]';
              lastDuration = Date.now() - start;
              success = true;
              break;
            } catch (err: any) {
              lastOutput = err.message;
              lastDuration = Date.now() - start;
              if (attempt < maxAttempts) {
                output += `  ⚠️  Attempt ${attempt} failed, retrying...\n`;
              }
            }
          }

          results.push({ name: step.name, status: success ? 'SUCCESS' : 'FAILED', output: lastOutput, duration: lastDuration });

          if (success) {
            output += `✅ ${step.name} (${lastDuration}ms)\n`;
            output += `   ${lastOutput.substring(0, 200)}${lastOutput.length > 200 ? '...' : ''}\n`;
          } else {
            output += `❌ ${step.name} FAILED after ${maxAttempts} attempt(s)\n`;
            output += `   ${lastOutput.substring(0, 300)}\n`;
            if (stopOnError) {
              output += `\n🛑 Pipeline stopped due to stopOnError=true\n`;
              break;
            }
          }
        }
      } else {
        // Parallel mode
        const promises = parsedSteps.map(async (step) => {
          const start = Date.now();
          try {
            const { stdout, stderr } = await execAsync(step.cmd, { cwd: workDir, timeout: 30000 });
            return { name: step.name, status: 'SUCCESS' as const, output: (stdout + stderr).trim() || '[no output]', duration: Date.now() - start };
          } catch (err: any) {
            return { name: step.name, status: 'FAILED' as const, output: err.message, duration: Date.now() - start };
          }
        });

        const parallelResults = await Promise.all(promises);
        for (const r of parallelResults) {
          results.push(r);
          const icon = r.status === 'SUCCESS' ? '✅' : '❌';
          output += `${icon} ${r.name} (${r.duration}ms)\n`;
          if (r.output) output += `   ${r.output.substring(0, 200)}${r.output.length > 200 ? '...' : ''}\n`;
        }
      }

      const successCount = results.filter(r => r.status === 'SUCCESS').length;
      const failCount = results.filter(r => r.status === 'FAILED').length;
      const skipCount = results.filter(r => r.status === 'SKIPPED').length;

      output += `\n══════════════════════════\n`;
      output += `Results: ${successCount} passed, ${failCount} failed, ${skipCount} skipped\n`;
      output += `══════════════════════════`;

      return output.trim();
    } catch (err: any) {
      return `Pipeline error: ${err.message}`;
    }
  }
};
